modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3 https://raw.githubusercontent.com/DrManganese/ender-crop/main/LICENSE"

[[mods]]
modId="endercrop"
version="${file.jarVersion}"
displayName="Ender Crop"
authors="DrManganese"
description="Mod which adds an ender pearl crop."

[[dependencies.endercrop]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.endercrop]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
