modLoader = "javafml"
loaderVersion = "[2,)"
license = "${mod_licence}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "logo-wide.png"
logoBlur = false

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
