name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: 1.17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        uses: eskatos/gradle-command-action@v2
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: false
          wrapper-directory: ./gradle/wrapper
          gradle-executable: ./gradlew
          arguments: build --no-daemon --max-workers 1
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/endercrop*.jar
