name: Gradle build

on:
  push:
    branches: [ '*' ]
  workflow_call:

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew --no-daemon common:build
  loader:
    runs-on: ubuntu-latest
    needs: [ common ]
    strategy:
      matrix:
        subproject: [fabric, neoforge]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew --no-daemon ${{ matrix.subproject }}:build
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.subproject}}-jar
          path: |
            ${{ matrix.subproject }}/build/libs/endercrop-*-${{ matrix.subproject }}.jar
