name: Build

on:
  workflow_dispatch
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  
jobs:
  verify:
    name: Compile 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Run tests
      run: sbt compile test
    - name: Publish Unit Test Reports
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "target/test-reports/*.xml"
    