name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  platforms:
    if: github.ref_type == tag && startsWith(github.ref_name, 'v*')
    environment: gradle
    name: Publish on Modrinth and CurseForge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & Release
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: false
          wrapper-directory: ./gradle/wrapper
          gradle-executable: ./gradlew
          arguments: platforms --no-daemon --max-workers 1 -PcurseforgeToken=${{secrets.CURSEFORGETOKEN}} -PmodrinthToken=${{secrets.MODRINTHTOKEN}}
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: ./build/libs/endercrop*.jar
  github:
    if: startsWith(github.ref, 'refs/tags/')
    name: Create GitHub Release
    needs: platforms
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./endercrop*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
