name: Release

on: [ workflow_call ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: actions-testing*.jar