name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run tests
        run: sbt package
      - name: List
        run: tree
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ./target/scala-2.13/actions-testing*.jar
